### ISSUE TITLE
Модель категории

### ISSUE THREAD

**Issue by temazinkin** [temazinkin/RiddleGame#9]
- [ ] Описать модель
- [ ] Выполнить миграцию
- [ ] Протестировать

**Comment by azinkindemo** [comment]
Какие поля модели взять?

**Comment by azinkindemo** [comment]
@temazinkin Я не понял

**Comment by temazinkin** [comment]
@azinkindemo Стоит подумать
Базовый набор:
- Название
- URL (уникальный)
- Описание (опционально)
- Родительская категория (опционально)
